### ISSUE TITLE
consider Types as string rather than int.

### ISSUE THREAD

**Issue by smoser** [anuvu/disko#50]
@tych0 brought up this question in https://github.com/anuvu/disko/pull/49.

In the initial design, @rchamarthy set up constants for "type identifiers" (`LVType`, `DiskType`, `AttachmentType`) using integer type and iota.

As I am (ab)using json as a output format, I then wrote marshallers and unmarshallers that display these types as strings and support reading them as integer or string.

@rchamarthy, could you give some reasoning for why we have:

    type LVType int
    const (
       THIN LVType = iota
       THICK
    )

rather than:

    type LVType string
    const (
       THIN = LVType("THIN")
       THICK = LVType("THICK")
    )

**Comment by rchamarthy** [comment]
@smoser  these to me are actually enums and i would like to use them as such in code. For example use them as index in an array etc. The go idiom is to go generate the boiler plate for making these types serializable to strings.

**Comment by smoser** [comment]
@rchamarthy thanks.  I did not know of go generate. Thats useful.

A few googles didn't show any hits for json usage we're doing, but thats fine.  we definitely could use go generate for many of the strings.  thanks.
